name: Sonarcloud

on:
  push:
    branches:
      - second

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Verify Java Files
      run: |
        cd Refactoring-Lab-master
        ls -l

    - name: Compile Java
      run: |
        cd Refactoring-Lab-master
        javac -d . *.java
