name: Sonarcloud

on:
  pull_request:
    branches:
      - second

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Verify Java Files
      run: |
        cd Refactoring-Lab-master
        find . -name "*.java"

    - name: Compile Java Files from Subdirectories
      run: |
        cd Refactoring-Lab-master
        find . -name "*.java" > sources.txt
        javac -d out @sources.txt
